[cr146][Android] Set `enable_glic_android` to `false` through config.js
There is inconsistency of enable_glic / enable_glic_android:
std::unique_ptr<glic::GlicProfileManager> glic_profile_manager_;

if (glic::GlicEnabling::IsEnabledByFlags()) {
glic_profile_manager_ = std::make_unique<glic::GlicProfileManager>();

Caused
../../chrome/browser/global_features.cc:111:5: error: use of undeclared identifier 'glic_profile_manager_'
111 |     glic_profile_manager_ = std::make_unique<glic::GlicProfileManager>();
  |     ^~~~~~~~~~~~~~~~~~~~~

Chromium change:
https://source.chromium.org/chromium/chromium/src/+/25209d29c5eccd5a4913804af9a5a4ce2a40156b

    set enable_glic=true

    Binary size is increased because this change brings in a lot of code to
    support Chrome Glic, which will be enabled in Chrome Android in the near
    future.

    Binary-Size: Size increase is unavoidable (see above).
    Bug: b:470059315
    Change-Id: I64aa5aca7192e571a83e8a3814f924db6a6a6964
    Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7454131